# Generated by Django 5.2.4 on 2025-08-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_due_today', 'Task Due Today'), ('task_due_tomorrow', 'Task Due Tomorrow'), ('task_reminder', 'Task Reminder'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
