# Generated by Django 5.2.6 on 2025-09-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_notification_related_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_due_today', 'Task Due Today'), ('task_due_tomorrow', 'Task Due Tomorrow'), ('task_reminder', 'Task Reminder'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('task_updated', 'Task Updated'), ('task_deleted', 'Task Deleted'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
