web: python manage.py migrate --noinput && python manage.py seed_celery_schedule && gunicorn server.wsgi:application --workers 3 --bind 0.0.0.0:$PORT
worker: celery -A server worker --loglevel=info
beat: celery -A server beat --loglevel=info
