# Generated by Django 5.2.4 on 2025-08-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='entity_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
