# Generated by Django 5.2.4 on 2025-07-21 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_model', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('avatar_color', models.CharField(default='#4285F4', max_length=20)),
                ('bot_nickname', models.CharField(default='Togetha AI', max_length=50)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('assistant', 'Assistant Message'), ('system', 'System Message')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
