# Generated by Django 5.2.4 on 2025-07-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-is_pinned', '-updated_at']},
        ),
        migrations.AddField(
            model_name='chatbotsetting',
            name='show_collapsed_sessions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='icon',
            field=models.CharField(blank=True, default='chat', max_length=50),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
