# Generated by Django 5.2.6 on 2025-10-02 03:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_conversationfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='doc_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
