# Generated by Copilot on 2025-10-29
from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_documentchunk_doc_id'),
    ]

    operations = [
        # Ensure the pgvector extension exists
        pgvector.django.VectorExtension(),
        # Add the vector field
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_vec',
            field=pgvector.django.VectorField(dimensions=768, null=True),
        ),
        # Optional: IVFFLAT index for cosine distance
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS chatbot_documentchunk_embedding_vec_ivfflat "
                "ON chatbot_documentchunk USING ivfflat (embedding_vec vector_cosine_ops) WITH (lists = 100);"
            ),
            reverse_sql=(
                "DROP INDEX IF EXISTS chatbot_documentchunk_embedding_vec_ivfflat;"
            ),
        ),
    ]
