"""Add doc_id to ConversationFile

Generated by automated edit
"""
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_documentchunk_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationfile',
            name='doc_id',
            field=models.UUIDField(null=True, blank=True),
        ),
    ]
