"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+^2p59aom-1u1r7%z0pg_vi4wg^y%10swf-=1!rpp!q6sr)q0p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*',  # Temporarily allow all hosts for testing
    '192.168.0.153',  # Local network IP, adjust as needed
    'localhost',
    '127.0.0.1',    
]

DEFAULT_FROM_EMAIL = 'kcorpuz_220000002183@uic.edu.ph'

# Email Configuration with ISP-resistant fallback
# Try multiple SMTP configurations to bypass ISP blocking
import os

# Use custom fallback backend for ISP-resistant email sending
# For development/testing in restricted networks, uncomment the line below:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Production email backend with automatic fallback
EMAIL_BACKEND = 'server.email_backend.FallbackSMTPBackend'

# Primary SMTP configuration (these will be tried by the fallback backend)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465  # SSL port - less commonly blocked than 587
EMAIL_USE_SSL = True  # Use SSL instead of TLS for port 465
EMAIL_USE_TLS = False  # Don't use TLS when using SSL
EMAIL_HOST_USER = 'wlage35@gmail.com'  # Your Gmail
EMAIL_HOST_PASSWORD = 'lbqi deda bbux ebxd'  # Your Gmail App Password

# Alternative: Use SendGrid for production (recommended for ISP-restricted environments)
# Uncomment these lines and sign up for SendGrid if Gmail continues to fail
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'apikey'
# EMAIL_HOST_PASSWORD = 'your-sendgrid-api-key'

# For console testing only (uncomment the line below to test locally)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Security settings
EMAIL_TIMEOUT = 60  # Increased timeout for slow connections
EMAIL_USE_LOCALTIME = False
 
# Timeout for Ollama/model API calls (seconds)
OLLAMA_TIMEOUT = 300

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'django_celery_beat', 
    'rest_framework',
    'rest_framework.authtoken', 
    'corsheaders',
    'notes',
    'chatbot',
    'task_manager',
    'notifications',
    'users',
    'logs',
    'scheduler',
    'usage_tracking',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'server.middleware.ClientTimezoneMiddleware',
    'django.middleware.common.CommonMiddleware',
    'server.middleware.CSRFExemptAPIMiddleware',  # Add before CSRF middleware
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'server.middleware.DebugAuthMiddleware',  # Our custom middleware
    'server.middleware.UserActivityMiddleware',  # Track user activity for scheduler
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CSRF_USE_SESSIONS = False  # Store CSRF in cookie instead
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access CSRF cookie
CSRF_COOKIE_SAMESITE = 'Lax'  # Less strict for better user experience
CSRF_TRUSTED_ORIGINS = ['http://localhost:3000', 'http://127.0.0.1:8000', 'http://192.168.0.153:8000']  # Add your frontend URLs

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # For development only, restrict in production
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Authorization',  # Explicit capitalization
]

ROOT_URLCONF = 'server.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://localhost:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

# # REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Add exception handler to provide better error messages
    'EXCEPTION_HANDLER': 'server.utils.custom_exception_handler',
    # Disable CSRF for API endpoints
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    # Ensure datetimes are timezone-aware and serialized in ISO 8601
    'DATETIME_FORMAT': 'iso-8601',
}
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'templates'), 
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email backend is configured above in the email section

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'email_debug.log',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'scheduler.tasks': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'server.email_backend': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.core.mail': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

TIME_ZONE = 'UTC'
USE_TZ = True

CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Use Redis as the message broker

CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Use Redis for storing task results


# Celery Task Settings
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Additional Celery settings for better reliability
CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_DISABLE_RATE_LIMITS = True