# Generated by Django 5.2.6 on 2025-10-18 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_time_seconds', models.IntegerField(default=0)),
                ('idle_time_seconds', models.IntegerField(default=0)),
                ('screen_changes', models.IntegerField(default=0)),
                ('interactions', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('navigation', 'Navigation'), ('interaction', 'Interaction'), ('chat', 'Chat Message'), ('task_create', 'Task Created'), ('task_complete', 'Task Completed'), ('note_create', 'Note Created'), ('note_edit', 'Note Edited'), ('file_upload', 'File Upload'), ('profile_update', 'Profile Update'), ('login', 'Login'), ('logout', 'Logout'), ('idle_start', 'Idle Started'), ('idle_end', 'Idle Ended')], max_length=50)),
                ('screen_name', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='usage_tracking.usersession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyUsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_active_time_seconds', models.IntegerField(default=0)),
                ('daily_average_seconds', models.IntegerField(default=0)),
                ('days_active', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_tasks_completed', models.IntegerField(default=0)),
                ('total_notes_created', models.IntegerField(default=0)),
                ('total_chat_messages', models.IntegerField(default=0)),
                ('total_interactions', models.IntegerField(default=0)),
                ('productivity_score', models.IntegerField(default=0)),
                ('consistency_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='DailyUsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_active_time_seconds', models.IntegerField(default=0)),
                ('total_idle_time_seconds', models.IntegerField(default=0)),
                ('session_count', models.IntegerField(default=0)),
                ('longest_session_seconds', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('notes_created', models.IntegerField(default=0)),
                ('notes_edited', models.IntegerField(default=0)),
                ('chat_messages', models.IntegerField(default=0)),
                ('file_uploads', models.IntegerField(default=0)),
                ('screen_changes', models.IntegerField(default=0)),
                ('total_interactions', models.IntegerField(default=0)),
                ('first_activity', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('peak_hour', models.IntegerField(blank=True, null=True)),
                ('average_response_time_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='usage_track_user_id_95e7b2_idx'), models.Index(fields=['date'], name='usage_track_date_025fed_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'start_time'], name='usage_track_user_id_6ce08f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_id'], name='usage_track_session_4ee9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active'], name='usage_track_is_acti_ddee78_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'timestamp'], name='usage_track_user_id_ddee38_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['session', 'timestamp'], name='usage_track_session_035f02_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type'], name='usage_track_activit_579569_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyusagesummary',
            index=models.Index(fields=['user', 'week_start'], name='usage_track_user_id_be24ba_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyusagesummary',
            index=models.Index(fields=['week_start'], name='usage_track_week_st_9feedc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyusagesummary',
            unique_together={('user', 'week_start')},
        ),
    ]
