# Generated by Django 5.2.4 on 2025-08-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_formatted_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='drawing_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='drawing_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='note_thumbnails/'),
        ),
        migrations.AddField(
            model_name='folder',
            name='has_drawing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='last_drawing_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
