# Generated by Django 5.2.5 on 2025-08-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_remove_folder_drawing_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="drawing_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text Note"),
                    ("voice", "Voice Note"),
                    ("image", "Image Note"),
                    ("drawing", "Drawing Note"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
