# Generated by Django 5.2.4 on 2025-08-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_folder_drawing_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='document_annotations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='drawing_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('text', 'Text Note'), ('voice', 'Voice Note'), ('image', 'Image Note'), ('drawing', 'Drawing Note'), ('document', 'Document Note')], default='text', max_length=10),
        ),
    ]
