# Generated by Django 5.2.6 on 2025-09-22 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_alter_note_drawing_data_alter_note_type"),
        ("notes", "0007_alter_tag_options_note_auto_save_count_and_more"),
    ]

    operations = []
