# Generated by Django 5.2.6 on 2025-09-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_merge_20250922_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('text', 'Text Note'), ('voice', 'Voice Note'), ('image', 'Image Note'), ('drawing', 'Drawing Note'), ('document', 'Document Note')], default='text', max_length=10),
        ),
    ]
