# Generated by Django 5.2.6 on 2025-10-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_note_last_accessed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tag',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.DeleteModel(
            name='AudioRecording',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
