# Generated by Django 5.2.6 on 2025-10-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_tag_unique_together_remove_tag_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='document_file',
        ),
        migrations.AddField(
            model_name='note',
            name='document_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='document_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='document_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
