# Generated by Django 5.2.6 on 2025-10-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_remove_note_document_file_note_document_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='note',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
