# Generated by Django 5.2.6 on 2025-10-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_note_document_file_note_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
