# Generated by Django 5.2.4 on 2025-09-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='username',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['email', 'username', 'verification_code'], name='users_email_email_510e20_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['expires_at'], name='users_email_expires_083d9c_idx'),
        ),
    ]
