# Generated by Django 5.2.5 on 2025-09-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_emailverification_email_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverification',
            name='users_email_email_510e20_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailverification',
            name='users_email_expires_083d9c_idx',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
