# Generated by Django 5.2.4 on 2025-07-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent_important', 'Do First (Urgent & Important)'), ('not_urgent_important', 'Schedule (Important, Not Urgent)'), ('urgent_not_important', 'Delegate (Urgent, Not Important)'), ('not_urgent_not_important', 'Eliminate (Not Urgent or Important)')], default='not_urgent_important', max_length=25),
        ),
    ]
