# Generated by Django 5.2.4 on 2025-07-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_task_options_remove_task_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', 'priority']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='task_manager.taskcategory'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.CharField(default='New Task', max_length=255),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='text',
            field=models.CharField(default='New Subtask', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent_important', 'Do First (Urgent & Important)'), ('not_urgent_important', 'Schedule (Important, Not Urgent)'), ('urgent_not_important', 'Delegate (Urgent, Not Important)'), ('not_urgent_not_important', 'Eliminate (Not Urgent or Important)')], default='not_urgent_important', max_length=25),
        ),
    ]
