# Generated by Django 5.2.4 on 2025-07-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_task_options_remove_task_completed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='title',
        ),
    ]
