# Generated by Django 5.2.4 on 2025-08-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_alter_task_options_remove_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due_date', '-priority', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_datetime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='subtask',
            name='text',
            field=models.CharField(default='Untitled Subtask', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent-important', 'Urgent and Important'), ('not-urgent-important', 'Not Urgent but Important'), ('urgent-not-important', 'Urgent but Not Important'), ('not-urgent-not-important', 'Not Urgent and Not Important')], default='not-urgent-not-important', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='Untitled Task', max_length=200),
        ),
    ]
