# Generated by Django 5.2.4 on 2025-08-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_rename_text_subtask_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='subject',
            new_name='category',
        ),
    ]
