# Generated by Django 5.2.4 on 2025-08-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_alter_task_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtask',
        ),
    ]
