# Generated by Django 5.2.4 on 2025-08-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0012_delete_subtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due_datetime', '-priority', '-created_at']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='due_datetime',
        ),
    ]
