# Generated by Django 5.2.6 on 2025-10-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0015_alter_task_options_alter_task_title_alter_task_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskCategory',
        ),
    ]
